---
- name: Create or update file using my_own_module from collection
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ my_own_module_path }}"
    content: "{{ my_own_module_content }}"
    force: "{{ my_own_module_force }}"
  register: file_operation_result

- name: Show info if file was changed
  debug:
    msg: "File {{ my_own_module_path }} was {{ 'created/updated' if file_operation_result.changed else 'already up to date' }}"
  when: file_operation_result.changed
